\chapter{Sprint 4 : Moteur de Recommandation LinUCB}

\section{Sprint Planning}

Entamé en janvier 2025, le quatrième Sprint s'est focalisé sur la transformation du système de la réactivité conversationnelle stricte vers la proactivité contextuelle autonome. Au cours de la cérémonie de Sprint Planning, le Product Owner a imposé l'implémentation du récit utilisateur exigeant : \enquote{\textit{En tant que système, je veux scorer une liste de recommandations en moins de 100 ms grâce au cache matriciel LinUCB}}. La mission prioritaire était donc d'ériger un moteur de recommandation robuste, émancipé des délais incompressibles de l'intelligence artificielle générative précédemment mise en œuvre.

Le Sprint Backlog s'est en conséquence structuré autour de l'algorithmique d'apprentissage par renforcement. Il requérait d'isoler mathématiquement les propriétés du visiteur, de tracer son comportement sur le frontend via un composant JavaScript ad hoc, et de bâtir un système de mise à jour matricielle en direct par modèle de bandits manchots (LinUCB).

La Definition of Done fixée pour valider cette itération imposait que la recommandation s'effectue et s'affiche sous un seuil drastique de latence fixé à 100 millisecondes, condition indispensable à l'utilisabilité d'un site de commerce de voyage, tout en démontrant une adaptation correcte en fonction des récompenses de traçage accumulées par l'internaute.

\section{Fondements mathématiques du bandit contextuel LinUCB}

La recommandation traditionnelle par filtrage collaboratif ou basé sur le contenu s'avère insuffisante pour du tourisme où le visiteur, souvent éphémère (problème structurel dit du \enquote{Cold Start}), varie ses attentes subitement dans la même session. Guidni adopte ainsi la théorie des bandits contextuels par l'équation LinUCB. La fondation de ce choix repose sur la projection combinatoire des attributs de l'utilisateur par rapport à son environnement.

Dans le modèle déployé sur l'application backend, les représentations sont construites autour du vecteur de caractéristiques noté $\phi$. Ce dernier est le produit tensoriel de deux sous-vecteurs essentiels. D'un côté, le contexte utilisateur $x_{\text{user}}$ de dimension $d=9$ englobant mathématiquement le sinus et le cosinus de l'heure et du mois garantissant la saisonnalité, la profondeur de défilement, le temps passé normalisé, et des affinités catégorielles de groupe. De l'autre, le profil du lieu $x_{\text{tags}}$, de dimension $d=34$, correspondant à un vocabulaire strict et stable (ex: \texttt{beach\_access}, \texttt{spa}, \texttt{wifi}). La dimension finale du vecteur croisé s'établit avec précision à $d_{\phi} = 306$.

Pour mémoriser les apprentissages globaux, une unique matrice de corrélation $\mathcal{A}$ de taille $306 \times 306$ et un vecteur cible $b$ de dimension $306$ sont initialisés. Ils sont partagés pour la totalité des éléments de l'inventaire dans la table \texttt{LinUCBGlobal}. L'espérance de score se résume alors à inférer formellement l'utilité temporelle tout en appliquant une majoration d'exploration supérieure ($\alpha$). Afin de maintenir un accès quasi instantané pour contourner le goulot d'étranglement relationnel (PostgreSQL), la matrice est exclusivement retenue et mutée dans la mémoire vive du serveur (RAM) via un système de verrouillage synchronisé (\texttt{threading.Lock}). La décharge sur la base de données n'est effectuée asynchronement que toutes les deux minutes moyennant la librairie APScheduler configurée sur le fuseau horaire de Tunis.

\section{Pipeline de classement en 10 étapes}

L'évaluation de la matrice n'est toutefois que le socle brut du classement. L'affichage final pour un utilisateur touristique exige la validation méticuleuse de contraintes budgétaires ou fonctionnelles pour garantir une pertinence sans faille. Le fichier d'orchestration logicielle (\texttt{ranker.py}) déploie ainsi un parcours impératif codifié rigoureusement en dix étapes de filtrage et de transformation séquentiels.

Le transit de tout candidat commence impérativement par (1) une correction de popularité, identifiant les entités dont l'exposition globale est insuffisante. S'applique après (2) le filtre temporel invalidant l'apparition d'un bar en matinée et (3) le filtre budgétaire l'assurant conforme aux souhaits explicites. Viens subséquemment la dimension tensorielle par (4) le calcul du vecteur composant $\phi$ et son intégration au (5) modèle de scoring LinUCB générant le classement initial.

Pour garantir une non-redondance cognitive fatale aux commerces de ce type, le top des classements affronte (6) un filtre de diversité figeant l'apparition maximale à un nombre de deux composants pour un même type de point touristique et forçant intrinsèquement (7) l'affichage inattendu d'au minimum une entité nouvelle (garantie de nouveauté). Intervient pour consolider la dispersion (8) la sélection aléatoire biaisée sur des tags méconnus réclamant à eux seuls 10\% des créneaux finaux. Enfin, le système applique (9) un tri à la marge pour le départage à commission équivalente et renvoie l'extraction mathématique formelle (10) d'un jeu top-k d'éléments au sous-système de distribution Next.js.

\section{Tracker comportemental et signaux de récompense}

L'architecture prédictive repose de fait sur la justesse empirique des métriques accumulées. Ces métriques proviennent frontalement de l'activité du voyageur glissant sur sa page de réservation. Pour assurer cette interconnexion silencieuse évitant le parasitage des temps de charge de l'API web, une directive de traçage passive rédigée en JavaScript vanilla, totalement dépourvue de dépendances tierces lourdes et compatible ESM, analyse le navigateur du client.

Ce traqueur consolide un tableau d'événements et décharge son lot au démantèlement du module d'interface utilisateur, principalement instruit sous la forme d'un envoi asynchrone balise (\texttt{beacon flush}) en fermeture. Il qualifie plusieurs attributs et attache une valeur de récompense numérique ($r$) selon un signal préétabli en backend : chaque impression vaut une base de 0.0, un clic basique se score à 0.3. Une consultation soutenue garantit des remontées importantes allant de 0.5 pour l'arrêt de 30 secondes à 0.7 pour le seuil d'une minute, confortée par le balayage d'une galerie d'images (0.4) ou des avis locaux (0.6). Le palier culmine avec la mise en liste de souhaits (\texttt{wishlist}) valorisée à 0.85 et l'acte de réservation ferme concédant un ratio maximal de 1.0. À l'encontre, l'algorithme sanctionne la sortie rapide avec rebond inférieur à 5 secondes avec un handicap de -0.2.

L'apprentissage est encadré par des orchestrateurs temporels cycliques nocturnes. Ces travailleurs invisibles dégradent mathématiquement le poids d'historique du vecteur du touriste (taux de décroissance temporelle de \texttt{ln(2)/30}), afin que son passif récent altère davantage la pondération en comparaison à ses errances informatiques d'un mois révolu. Une routine additionnelle se charge de corriger en cas de dérive conceptuelle saisonnière le coefficient tous les quatre-vingt-dix jours.

\section{Sprint Review \& Retrospective}

Lors du passage collégial caractérisant la fin d'itération formalisant la Sprint Review finale de ce bloc, l'équipe a éprouvé la solution face au Scrum Master. L'ingestion d'une centaine de frappes événementielles via Postman a abouti à une rotation du dictionnaire qualifiant l'environnement hôtelier en faveur de séjours maritimes. La restriction primordiale sous les 100 millisecondes a été démontrée conforme, les chronomètres de l'API validant les inférences de classements bruts oscillant aux alentours des cinq à dix millisecondes en condition locale.

Lors de la Sprint Retrospective associée, une réflexion intense portait sur la pertinence structurelle d'une évaluation complète. Disposant alors de l'infrastructure RAG connectée à l'univers d'exploration et couverte par la sélection mathématique LinUCB, le système se devait d'être intégralement mis en lumière par une assurance qualité d'envergure. Cette conclusion de développement initie nécessairement le dernier cycle consacré globalement et explicitement aux tests et aux déploiements, afin de confirmer l'hypothèse centrale portée par la problématique du diplôme.

\section*{Conclusion du chapitre}
\addcontentsline{toc}{section}{Conclusion du chapitre}

Ce Chapitre 4 documente la finalisation algorithmique de la plateforme Guidni par la création du moteur autonome de recommandation hybridé au truchement du Sprint 4. Se détachant du modèle cognitif strict de l'agent, le dispositif en dix boucles de classement dépose mathématiquement le visiteur en une variable contextualisée subissant l'équation UCB à récompenses fractionnées de 0.3 à 1.0. La résolution majeure face au péril asynchrone repose concrètement sur une implémentation logicielle stockant et exploitant par verrou sur mémoire vive (RAM) l'équation matricielle, n'imposant qu'une réconciliation base de données décousue du fil de vue frontend. Le système de fondations mathématiques étant scellé, le Chapitre 5 détaillera dorénavant la méthode analytique globale et l'évaluation macroscopique confirmant l'exactitude de ces postulats théoriques assemblés sur les cinq derniers mois.